### PR TITLE
Update testPersona.php

### PR DESCRIPTION
**Pull request by suriyaa**
@mozilla @fmarier @ccarruitero @ryuslash @hdorio @chilts @SyntaxC4 @ozten @DeadSuperHero @ScottDowne @simonwex 

---

Hi _mozilla contributors_, :smile:

I close the **css-link**.

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

### CODE REVIEW

**Comment by abackstrom** [comment]
:+1:

**Comment by SuriyaaKudoIsc** [comment]
@mozilla

**Comment by ozten** [comment]
Conflicts, otherwise I would merge.

**Comment by suriyaa** [comment]
Why?

**Comment by hdorio** [comment]
@SuriyaaKudoIsc pull request #50 was somehow merged before this one for the same fix.

**Comment by suriyaa** [comment]
:unamused:

**Pull request closed without merging**
